// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hopfiyxeqbdrfpdfslpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvcGZpeXhlcWJkcmZwZGZzbHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODU2OTksImV4cCI6MjA2NTA2MTY5OX0.WteZ3WQ03Pz2H9omGpXP9d10qQU9P5i8rqrQVirRt4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);